"""add is_published in news table

Revision ID: 372ac2be95a1
Revises: 
Create Date: 2022-03-19 16:06:49.784452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372ac2be95a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('association')
    op.drop_table('category')
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team_leader', sa.INTEGER(), nullable=True),
    sa.Column('job', sa.VARCHAR(), nullable=True),
    sa.Column('work_size', sa.INTEGER(), nullable=True),
    sa.Column('collaborators', sa.VARCHAR(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('is_finished', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['team_leader'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('news', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['news'], ['news.id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('about', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('is_private', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
